url: "https://ukiyoserver.live/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "beta" # the subpath of your site, e.g. /blog
title: "Beta Ukiyo" # the name of your site, e.g. ACME Corp.
